### PR TITLE
Set up mavros and logging

### PR DESCRIPTION
**Pull request by clydemcqueen**
* add a launch file and yaml files to launch `mavros` and `ros2 bag record`
* README.md has notes for the operator / pilot
* modify the .gitignore to make my life a bit easier

### CODE REVIEW

**Comment by billmania** [comment]
I like this implementation.

**Comment by clydemcqueen** [comment]
I added logging of local_position, which is the output of the EKF. I wouldn't trust the x and y coords, but the z coord should be good. We'll have to try it tomorrow.

**Comment by clydemcqueen** [comment]
Also: I figured out that `/mavros/imu/temperature_baro` is from the SCALED_PRESSURE msg, which is the Pixhawk temperature. No point in logging that. The actual water temperature from the Bar30 is published in the SCALED_PRESSURE2 msg, which mavros doesn't handle. If we want it, we'll need to modify mavros (mavros_extras, probably) or create a simple Python node that does the equivalent.

**Comment by billmania** [comment]
The new X150Status message (which you can now see) includes water temperature, pressure, and depth from the X150. rosbag-ing the /x150_status topic will add those measurements to the bag.

**Pull request merged**
